server:
  port: 80
spring:
  freemarker:
    expose-session-attributes: true

# dubbo
dubbo:
  application:
    id: baoJieWeb
    name: baoJieWeb
    qosEnable: false
  registry:
    id: baoJieZookeeper
    address: zookeeper://119.29.239.91:2181?client=curator
